export const style = {
    container: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#ccc',
        position: 'relative',
    },
    productDetail: {
        width: '100%',
        padding: 20,
        backgroundColor: '#fff'
    },
    itemWrapper: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    itemImg: {
        width: 110,
        height: 150,
    },
    itemDetail: {
        width: '65%',
    },
    itemTxt: {
        fontFamily: 'Roboto',
        fontSize: 14,
        fontWeight: 700,
        marginBottom: 10,
    },
    price: {
        color: '#EE0D0D',
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        marginBottom: 10,
    },
    priceBefore: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
        position: 'relative',
        color: '#808080',
        marginBottom: 10,
    },
    line: {
        width: 50,
        height: 2,
        position: 'absolute',
        bottom: 59,
    },
    number: {
       display: 'flex',
       flexDirection: 'row',
       justifyContent: 'space-between',
    },
    numberWrapper: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center'
    },  
    btn: {
        width: 15, 
        height: 15,
        backgroundColor: '#ccc',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnIncTxt: {
        width: 10,
        paddingBottom: 3,
    },
    btnDescTxt: {
        width: 10,
        paddingBottom: 3,
        paddingLeft: 2,
    },
    numberTxt: {
        paddingLeft: 5,
        paddingRight: 5,
        marginTop: -1,
        fontFamily: 'Roboto',
        fontSize: 15,
        fontWeight: 700,
    },
    buyAfter: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
        color: '#134fec',
    },
    saveDiscount: {
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        marginTop: 20,
    },
    saveDiscountTxt: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
    },
    seeSaveDiscount: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
        color: '#134FEC',
        marginLeft: 20,
    },
    discountWrapper: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 30,
        width: '100%',
        position: 'relative',
    },
    discountInput: {
        borderRadius: 2,
        borderStyle: 'solid',
        borderWidth: 2,
        borderColor: '#ccc',
        width: 208,
        paddingLeft: 50,
    },
    discountBlock: {
        width: 32,
        height: 16,
        backgroundColor: '#F2DD1B',
        marginLeft: 10,
        marginRight: 10,
        position: 'absolute',
        top: 15,
    },
    discountTxt: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        marginTop: -2,
    },
    applyBtn: {
        width: 100,
        height: 45,
        backgroundColor: '#134FEC',
        borderRadius: 2,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    applyTxt: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        color: '#fff',
    },
    presentWrapper: {
        padding: 20,
        display: 'flex', 
        flexDirection: 'row',
        backgroundColor: '#fff',
        width: '100%',
        marginTop: 30,
    },
    presentTxt: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
    },
    type: {
        fontFamily: 'Roboto',
        fontSize: 12,
        fontWeight: 700,
        color: '#134FEC',
        marginLeft: 20,
    },
    moneyWrapper: {
        width: '100%',
        backgroundColor: '#fff',
        marginTop: 30,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 20,
    },
    calcTxt: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
    },
    money: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        color: '#EE0D0D',
    },
    lastMoneyWrapper: {
        width: '100%', 
        backgroundColor: '#fff',
        padding: 20,
        float: 'bottom',
        position: 'absolute',
        bottom: 0,
    },
    lastMoneyTxtWrapper: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    lastMoneyTxt: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        color: '#808080'
    },
    lastMoney: {
        fontFamily: 'Roboto',
        fontSize: 18,
        fontWeight: 700,
        color: '#EE0D0D',
    },
    btnOrder: {
        width: '100%',
        height: 45,
        marginTop: 20,
        backgroundColor: '#E53935',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 2,
    },
    orderTxt: {
        fontFamily: 'Roboto',
        fontSize: 20,
        fontWeight: 700,
        color: '#fff',
    },
}